// <auto-generated />
using System;
using Demo.Repository.Pattern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Demo.Repository.Pattern.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20221122191345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Demo.Repository.Pattern.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.01);

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("UpdatedOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 11, 22, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1583),
                            Name = "Product One",
                            UnitPrice = 1.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 11, 22, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1585),
                            Name = "Product Two",
                            UnitPrice = 2.5
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 6, 25, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1585),
                            Name = "Old Product",
                            UnitPrice = 3.5499999999999998,
                            UpdatedOn = new DateTime(2022, 11, 22, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1596)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 11, 22, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1597),
                            Name = "Expensive Product",
                            UnitPrice = 150.99000000000001,
                            UpdatedOn = new DateTime(2022, 11, 22, 19, 13, 45, 503, DateTimeKind.Utc).AddTicks(1597)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
